version: '3.8'
services:
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    deploy:
      replicas: 1
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia